# Generated by Django 4.1.7 on 2023-03-16 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('primaryKey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pixel', models.ImageField(upload_to='general/files/')),
                ('data', models.CharField(default='HistoryDataServiceProvider', max_length=1000)),
            ],
        ),
    ]
