# Generated by Django 4.1.7 on 2023-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='link',
            field=models.CharField(default='HistoryLinkServiceProvider', max_length=150),
        ),
        migrations.AlterField(
            model_name='history',
            name='pixel',
            field=models.ImageField(blank=True, null=True, upload_to='general/files/'),
        ),
    ]
